### ISSUE TITLE
Error reporting 

### ISSUE THREAD

**Issue by sleeperzjf** [notsebastiano/transfer_entropy#1]
![image](https://user-images.githubusercontent.com/65698607/87372989-5f7ff900-c5bb-11ea-9ed1-d0a45386b7f9.png)

![image](https://user-images.githubusercontent.com/65698607/87372929-4a0acf00-c5bb-11ea-8c13-2911f94f3c30.png)

**Comment by notsebastiano** [comment]
Issue solved - problem was due to code not updated to python3
